### ISSUE TITLE
libbz2.so.1.0 is missing for some builds

### ISSUE THREAD

**Issue by bazinski** [SouthAfricaDigitalScience/fitsio-deploy#5] opened 2017-03-28 18:44 UTC
/usr/bin/ld: warning: libbz2.so.1.0, needed by ./libcfitsio.so, not found (try using -rpath or -rpath-link)
./testprog: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory

This only happens for builds on centos for version 3410, 3370 works fine :(

**Comment by brucellino** [comment] 2017-03-29 08:14
The bzlib that is provided is 1.0.6 : 
```
module  add  bzip2
becker@serbaggio:~$ ls $BZLIB_DIR/lib
libbz2.a  libbz2.so  libbz2.so.1.0.6

```

this can probably be fixed by taking a look at the generated make targets.

**Comment by bazinski** [comment] 2017-03-29 08:17
sure but they are all pulling in the same bzlib and it works in all but the centos6/7 on the later version of fitsio

**Comment by brucellino** [comment] 2017-03-29 08:42
So, the builds are failing only for the newer version of fitsio. I can't reproduce this on my laptop. The build is indeed linking to the correct `libbz2`. I think this may have to do with running testprog from the build dir instead of the installed version. working on a fix now.

**Closed as completed** 2017-05-07 15:31 UTC
Labels: bug
